### ISSUE TITLE
Error, module missing?

### ISSUE THREAD

**Issue by zampy93** [StuartLab/MiNA#11]
Hello, i am trying MiNa through Fiji. I installed everything following the installation guide. I also tried updating Fiji. I always get the same Error (see the console log below). It is not clear to me how to get that missing module, i don't have pip in this computer (and i doubt i could install it), but i don't think it would work anyway.

[ERROR] null
Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: No module named eztables

	at org.python.core.Py.ImportError(Py.java:334)
	at org.python.core.imp.import_first(imp.java:879)
	at org.python.core.imp.import_module_level(imp.java:964)
	at org.python.core.imp.importName(imp.java:1057)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1280)
	at org.python.core.PyObject.__call__(PyObject.java:450)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1076)
	at org.python.pycode._pyx6.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx6.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ScienceToolkit** [comment]
Hello,

Can you provide a few more details and I will try to reproduce the problem when I get a chance?

1. Was this installed using the update site as described in the up to date project [wiki page](https://imagej.net/MiNA_-_Mitochondrial_Network_Analysis#Installation)?

2. What operating system is your computer running?

3. Which version of Fiji is installed?

Cheers,
Andrew

**Comment by zampy93** [comment]
Hello,

1) Yes. 

2) Windows 7 Pro

3) I downloaded fiji yesterday from the website so i suppose is the latest version. 

I finally managed to go around the problem. When opening an image (i'm using .zvi files) if i change the Stack viewing from Hyperstack to Standard ImageJ the error doesn't come up. In this case i noticed that the overlay after running the macro is shifted to the left, it seems precise, just shifted. 

Cheers,
Luca

**Comment by ScienceToolkit** [comment]
The error message you described seems odd given that it must have found the module it when you switched from a HyperStack to Stack if it ran after that. Not sure why that would be dependent on how the image is represented. I will see if I can reproduce the error when I get a chance.

I think I found the source of the overlay shift. Were you using a selected ROI? The code allows for ROIs to be selected. That is carried out by the following section of code:

https://github.com/StuartLab/MiNA/blob/dc02fc7c25738c323755bcc6461bf4faeec2af93/src/MiNA_Analyze_Morphology.py#L125-L133

Later on, the overlay is generated (2D case) with the following snippet:
https://github.com/StuartLab/MiNA/blob/dc02fc7c25738c323755bcc6461bf4faeec2af93/src/MiNA_Analyze_Morphology.py#L219-L237

Lines 225 and 228 place the overlay's upper corner at 0,0 or the upper left corner. Is that where it was being positioned for you? If so, I will have to see if I can capture the selected region's bounds and feed them in for positioning - I think it's possible.

**Comment by admaguire** [comment]
Hello, I am having the exact same issue with the "eztables" error code on MiNa. I tried to open as standard image J rather than hyperstack but this did not fix the problem. 

I have a mac that runs Catalina, and my Fiji says it is version 1, although it was downloaded quite recently. The one thing I can fathom that could cause this problem is that I downloaded the python script from github and plugged it into Fiji that way (since currently the actual Fiji site is down).

**Comment by RodoVJ** [comment]
Unfortunately, the script can't be manually installed at this time. Alternatively, you could look at:
* [Mitochondria-Analyzer](https://github.com/AhsenChaudhry/Mitochondria-Analyzer)
* [MitoGraph](https://github.com/vianamp/MitoGraph)
* [Mito-Morphology](https://imagejdocu.tudor.lu/plugin/morphology/mitochondrial_morphology_macro_plug-in/start)
* [Momito](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005612)

A manually install-able version of MiNA will be available but we cannot say how long until we release it.

**Comment by admaguire** [comment]
Hi, 

Thank you for your quick reply! Our lab has been using MiNA for close to a year now, but the person who was running the analysis with MiNA left (hence the need for download). Do you know how long it might be before the site is up and running again for regular installation?

Best, 
Aislinn

**Comment by imagejan** [comment]
> Do you know how long it might be before the site is up and running again for regular installation?

Updating from any update site via the updater should be working by now. It's really only the wiki that is currently still offline. Please see [this forum topic](https://forum.image.sc/t/imagej-wiki-is-down/39672?u=imagejan) for updates.
