### ISSUE TITLE
error

### ISSUE THREAD

**Issue by samin096** [StuartLab/MiNA#14]
[INFO] Reading available sites from https://imagej.net/
[INFO] Reading available sites from https://imagej.net/
console: Failed to install '': java.nio.charset.UnsupportedCharsetException: cp0.
[ERROR] Traceback (most recent call last):
  File "MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: No module named eztables

**Comment by samin096** [comment]
i cannot use mina

**Comment by RodoVJ** [comment]
Hello,

It seems like you're missing a library. Please try running the updater on Fiji (Help → Update...). If that fails, reinstall Fiji and add the update sites as described in the installation section of the [MiNA Wiki Page](https://imagej.net/MiNA_-_Mitochondrial_Network_Analysis#Installation).

Cheers,
Rodrigo

**Comment by samin096** [comment]
Tried that- still having the same problem. Is there a way to get the branch length and branch counts without using MiNA. I can get the footprint and also the ridges

**Comment by samin096** [comment]
java.lang.NullPointerException
    at org.scijava.script.ScriptModule.getEngine(ScriptModule.java:108)
    at org.scijava.script.ScriptModule.run(ScriptModule.java:129)
    at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
    at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
    at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
    at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
[Sun Apr 19 19:13:22 CST 2020] [ERROR] [] null
Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 291, in <module>
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 101, in run
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: java.lang.NullPointerException

    at org.python.core.Py.JavaError(Py.java:552)
    at org.python.core.Py.JavaError(Py.java:543)
    at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:190)
    at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:206)
    at org.python.core.PyObject.__call__(PyObject.java:480)
    at org.python.core.PyObject.__call__(PyObject.java:484)
    at org.python.core.PyMethod.__call__(PyMethod.java:126)
    at org.python.pycode._pyx0.run$2(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:287)
    at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:171)
    at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
    at org.python.core.PyFunction.function___call__(PyFunction.java:471)
    at org.python.core.PyFunction.__call__(PyFunction.java:466)
    at org.python.core.PyFunction.__call__(PyFunction.java:456)
    at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
    at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
    at org.python.core.PyTableCode.call(PyTableCode.java:171)
    at org.python.core.PyCode.call(PyCode.java:18)
    at org.python.core.Py.runCode(Py.java:1614)
    at org.python.core.__builtin__.eval(__builtin__.java:497)
    at org.python.core.__builtin__.eval(__builtin__.java:501)
    at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
    at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
    at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
    at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
    at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
    at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
    at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
    at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
    at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:228)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.NullPointerException
    at java.util.concurrent.FutureTask.report(FutureTask.java:122)
    at java.util.concurrent.FutureTask.get(FutureTask.java:192)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.python.core.PyReflectedFunction.__call__(PyReflectedFunction.java:188)
    ... 31 more
Caused by: java.lang.NullPointerException
    at org.scijava.script.ScriptModule.getEngine(ScriptModule.java:108)
    at org.scijava.script.ScriptModule.run(ScriptModule.java:129)
    ... 8 more

**Comment by RodoVJ** [comment]
We will try to replicate this issue and investigate this further. In the mean time you could use [Mitochondria-Analyzer](https://github.com/AhsenChaudhry/Mitochondria-Analyzer
) as an alternative. You can read more about it [here](https://doi.org/10.1152/ajpendo.00457.2019).
