### ISSUE TITLE
ImportError: compiled unit contains version 37 code (38 required)

### ISSUE THREAD

**Issue by ardejani** [StuartLab/MiNA#19]
I am getting the following error, could you please suggest a work around this?

[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): /Applications/Fiji.app/jars/Lib/eztables/__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx2.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx2.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RodoVJ** [comment]
Hi ardejani! Please try installing the newest version of MiNA. This his has to be manually installed and cannot be obtained through the update site. Follow the installation instructions of the README of this repository. Please let us know if you have any further issues.

**Comment by FX-Xu** [comment]
Hi, I have installed the newest mac (10.15.6) version of MiNA. FIJI/imageJ version is 1.53c. My working flow is: open TIFF file, select one cell, clear outside, filter->unsharp mask, CLAHE, change to 8bit, open MiNA plugin. But it pops up the following error:

[Tue Sep 22 12:50:08 CST 2020] [ERROR] [] null
Traceback (most recent call last):
  File "/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py", line 273, in <module>
    run(imp, preprocessor_path, postprocessor_path, threshold_method, user_comment)
  File "/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py", line 242, in run
    morphology_tbl.writeRow(output_parameters, mina.tables.commentToDict(user_comment))
  File "/Applications/Fiji.app/jars/Lib/mina/tables/_simplesheet.py", line 57, in writeRow
    self.rt.addValue(key, str(value))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-16: ordinal not in range(128)

	at org.python.core.codecs.strict_errors(codecs.java:206)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.python.core.JavaFunc.__call__(Py.java:2895)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.codecs.encoding_error(codecs.java:1537)
	at org.python.core.codecs.PyUnicode_EncodeIntLimited(codecs.java:1210)
	at org.python.core.codecs.PyUnicode_EncodeASCII(codecs.java:1169)
	at org.python.core.codecs.encode(codecs.java:163)
	at org.python.core.PyString.encode(PyString.java:3995)
	at org.python.core.PyString.encode(PyString.java:3987)
	at org.python.core.PyUnicode.unicode___str__(PyUnicode.java:681)
	at org.python.core.PyUnicode.__str__(PyUnicode.java:676)
	at org.python.core.PyString.str_new(PyString.java:172)
	at org.python.core.PyString$exposed___new__.new_impl(Unknown Source)
	at org.python.core.PyType.invokeNew(PyType.java:1119)
	at org.python.core.PyType.type___call__(PyType.java:2399)
	at org.python.core.PyType.__call__(PyType.java:2389)
	at org.python.core.PyObject.__call__(PyObject.java:461)
	at org.python.core.PyObject.__call__(PyObject.java:465)
	at mina.tables._simplesheet$py.writeRow$3(/Applications/Fiji.app/jars/Lib/mina/tables/_simplesheet.py:52)
	at mina.tables._simplesheet$py.call_function(/Applications/Fiji.app/jars/Lib/mina/tables/_simplesheet.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:158)
	at org.python.core.PyFunction.__call__(PyFunction.java:437)
	at org.python.core.PyMethod.__call__(PyMethod.java:156)
	at org.python.pycode._pyx1.run$8(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py:263)
	at org.python.pycode._pyx1.call_function(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
	at org.python.core.PyFunction.function___call__(PyFunction.java:474)
	at org.python.core.PyFunction.__call__(PyFunction.java:469)
	at org.python.core.PyFunction.__call__(PyFunction.java:459)
	at org.python.pycode._pyx1.f$0(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py:273)
	at org.python.pycode._pyx1.call_function(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ardejani** [comment]
> Hi ardejani! Please try installing the newest version of MiNA. This his has to be manually installed and cannot be obtained through the update site. Follow the installation instructions of the README of this repository. Please let us know if you have any further issues.

I installed the latest MiNA (3.0.0) and still get the same error.

**Comment by RodoVJ** [comment]
> > Hi ardejani! Please try installing the newest version of MiNA. This his has to be manually installed and cannot be obtained through the update site. Follow the installation instructions of the README of this repository. Please let us know if you have any further issues.
> 
> I installed the latest MiNA (3.0.0) and still get the same error.

Please make sure you are running the new plugin, you might be running the old MiNA since they have the same name and both are under StuartLab. MiNA 3.0.0 does not makes use of the eztables module.

**Comment by RodoVJ** [comment]
> Hi, I have installed the newest mac (10.15.6) version of MiNA. FIJI/imageJ version is 1.53c. My working flow is: open TIFF file, select one cell, clear outside, filter->unsharp mask, CLAHE, change to 8bit, open MiNA plugin. But it pops up the following error:
> 
> [Tue Sep 22 12:50:08 CST 2020] [ERROR] [] null
> Traceback (most recent call last):
> File "/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py", line 273, in 
> run(imp, preprocessor_path, postprocessor_path, threshold_method, user_comment)
> File "/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py", line 242, in run
> morphology_tbl.writeRow(output_parameters, mina.tables.commentToDict(user_comment))
> File "/Applications/Fiji.app/jars/Lib/mina/tables/_simplesheet.py", line 57, in writeRow
> self.rt.addValue(key, str(value))
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 13-16: ordinal not in range(128)
> 
> ```
> at org.python.core.codecs.strict_errors(codecs.java:206)
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> at java.lang.reflect.Method.invoke(Method.java:498)
> at org.python.core.JavaFunc.__call__(Py.java:2895)
> at org.python.core.PyObject.__call__(PyObject.java:433)
> at org.python.core.codecs.encoding_error(codecs.java:1537)
> at org.python.core.codecs.PyUnicode_EncodeIntLimited(codecs.java:1210)
> at org.python.core.codecs.PyUnicode_EncodeASCII(codecs.java:1169)
> at org.python.core.codecs.encode(codecs.java:163)
> at org.python.core.PyString.encode(PyString.java:3995)
> at org.python.core.PyString.encode(PyString.java:3987)
> at org.python.core.PyUnicode.unicode___str__(PyUnicode.java:681)
> at org.python.core.PyUnicode.__str__(PyUnicode.java:676)
> at org.python.core.PyString.str_new(PyString.java:172)
> at org.python.core.PyString$exposed___new__.new_impl(Unknown Source)
> at org.python.core.PyType.invokeNew(PyType.java:1119)
> at org.python.core.PyType.type___call__(PyType.java:2399)
> at org.python.core.PyType.__call__(PyType.java:2389)
> at org.python.core.PyObject.__call__(PyObject.java:461)
> at org.python.core.PyObject.__call__(PyObject.java:465)
> at mina.tables._simplesheet$py.writeRow$3(/Applications/Fiji.app/jars/Lib/mina/tables/_simplesheet.py:52)
> at mina.tables._simplesheet$py.call_function(/Applications/Fiji.app/jars/Lib/mina/tables/_simplesheet.py)
> at org.python.core.PyTableCode.call(PyTableCode.java:173)
> at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
> at org.python.core.PyBaseCode.call(PyBaseCode.java:158)
> at org.python.core.PyFunction.__call__(PyFunction.java:437)
> at org.python.core.PyMethod.__call__(PyMethod.java:156)
> at org.python.pycode._pyx1.run$8(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py:263)
> at org.python.pycode._pyx1.call_function(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py)
> at org.python.core.PyTableCode.call(PyTableCode.java:173)
> at org.python.core.PyBaseCode.call(PyBaseCode.java:306)
> at org.python.core.PyFunction.function___call__(PyFunction.java:474)
> at org.python.core.PyFunction.__call__(PyFunction.java:469)
> at org.python.core.PyFunction.__call__(PyFunction.java:459)
> at org.python.pycode._pyx1.f$0(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py:273)
> at org.python.pycode._pyx1.call_function(/Applications/Fiji.app/scripts/MiNA_Analyze_Morphology.py)
> at org.python.core.PyTableCode.call(PyTableCode.java:173)
> at org.python.core.PyCode.call(PyCode.java:18)
> at org.python.core.Py.runCode(Py.java:1687)
> at org.python.core.__builtin__.eval(__builtin__.java:497)
> at org.python.core.__builtin__.eval(__builtin__.java:501)
> at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
> at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
> at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
> at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
> at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
> at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
> at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
> at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
> at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
> at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> at java.lang.Thread.run(Thread.java:748)
> ```

Hello, are you able to see the interface of MiNA at all? Or does this inly happen when you press “OK”. Also, please try to open a new issue since this is separate from @ardejani ‘s issue.

**Comment by ardejani** [comment]
Thanks @RodoVJ ! After removing the StuartLab directory and reinstalling MiNA 3.0.0, the issue is resolved.

**Comment by RodoVJ** [comment]
That's good to hear @ardejani !
