### ISSUE TITLE
Error when trying to use MiNa

### ISSUE THREAD

**Issue by marcusburi** [StuartLab/MiNA#22]
Hello, 

When I try to run MiNa from Fiji, I get this error, what could be?

Thanks

[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): /Applications/Fiji.app/jars/Lib/eztables/__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RodoVJ** [comment]
Hi @marcusburi ! Please try installing the newest version of MiNA. This his has to be manually installed and cannot be obtained through the update site. Follow the installation instructions of the README of this repository. Please let us know if you have any further issues. It is listed as MiNA 3.0.0.

**Comment by marcusburi** [comment]
Thank you  Rodrigo.  I'll give it a try

Em seg, 5 de out de 2020 16:50, Rodrigo Vega <notifications@github.com>
escreveu:

**Comment by boydk4** [comment]
I have this same issue. I reinstalled MiNA 3.0.0 and I still get this error:

[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Users\kati3\Desktop\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SophieLAllen** [comment]
Hi, I am also having the same issue as the above. I have installed version 3.0.0 and deleted the Stuart lab folder from the plugins folder. Is there anything else you would suggest changing to bypass the error message please?

Many Thanks!
