### ISSUE TITLE
MiNA ImagePlus

### ISSUE THREAD

**Issue by ak1920** [StuartLab/MiNA#23]
Hi,
I hope you are all well, 
I installed all the parts of MiNA as you kindly explained in read.me section. When I tried to run it gave me a warning saying 'ImagePlus is required but none exists'.
I googled but could not find how to include it in MiNA,
Many thanks for helping in advance,

**Comment by RodoVJ** [comment]
Hi,
Before running Mina you have to have an image open. Please try opening an image first and then running the tool.

**Comment by ak1920** [comment]
Thank you, I did,
unfortunately  it ran without giving a result and got this error message:

[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): /Applications/Fiji.app/jars/Lib/eztables/__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ak1920** [comment]
I read your answer to the previous issue, which has the same error with mine,
if the answer will be the same, could you suggest where to download the newer version, I  downloaded the zip from this site.

**Comment by RodoVJ** [comment]
If you go to the “code” tab of this repository, you should see a green button near the top right that says “code”. Click on it and download the zip folder. Alternatively, you could go to “releases” and download MiNA 3.0.0. Make sure you’re not running the old version of the script since they have the same name. You can always delete the StuartLab repository located in Plugins/Stuartlab in your Fiji installation.

**Comment by awardyn1** [comment]
Hello! @RodoVJ Thank you for the reply. Reinstalling the plugin as you suggested worked very well for me!

**Comment by RodoVJ** [comment]
Glad to hear that :) @awardyn1

**Comment by Joey-Casalini** [comment]
Hello, I have installed the new version and deleted the Stuart Lab plugin. But now that I've deleted the plugin I don't know how to run the tool! Could you give me a step-by-step? I can find many references to 'Processing pipeline and usage' guidelines, but I cant actually find them! Could someone please provide a link? Thanks so much.
