### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kaccfite** [StuartLab/MiNA#32]
Hi, I try to run the MiNA, But I failed everytime
Could you help me to figure out this problem?
Thank you!

[INFO] Reading available sites from https://imagej.net/
[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Yanqiao Lu store\fiji-win64\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Yanqiao Lu store\fiji-win64\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx1.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx1.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Yanqiao Lu store\fiji-win64\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx2.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx2.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Yanqiao Lu store\fiji-win64\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx3.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx3.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Yanqiao Lu store\fiji-win64\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx4.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx4.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RodoVJ** [comment]
Please try installing the newest version of MiNA. This his has to be manually installed and cannot be obtained through the update site. Follow the installation instructions of the [README ](https://github.com/StuartLab/MiNA#installation)of this repository. 
If you are still having issues after this, delete the StuartLab folder inside Plugins or change the name of StuartLab/MiNA_scripts/MiNA_Analyze_Morphology.py (which is the old version) to something else so you can differentiate between the two.

Hope this helps!

**Comment by kaccfite** [comment]
Hi,
I reinstall the plugin and run it again.
Here is another error  code.
***@***.***D73601.8D1D8BF0]
Could you help me to figure it out?
Thank you sooo much!
Yanqiao
Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by RodoVJ** [comment]
Hi, would you mind telling me the steps you're doing that lead you to getting the error message? Also, would that be the complete error message?

**Comment by kaccfite** [comment]
Yes, that is the complete message.
I open an picture first. And then select a cell with rectangle.
Then I change the image from 32 bit to 8 bit.
Then I run the MiNA
Choose the “OK” button without any change.
That’s all.
I can get a result like this. And with an error code that I showed you before.
***@***.***D7360C.6A9C61E0]

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Rodrigo ***@***.***>
发送时间: 2021年4月20日 17:32
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [StuartLab/MiNA] Error (#32)


Hi, would you mind telling me the steps you're doing that lead you to getting the error message? Also, would that be the complete error message?

―

**Comment by RodoVJ** [comment]
Which version of MiNA are you using? What does the user interface look like? Also, do you still get the error if you don't convert to 8-bit?

**Comment by kaccfite** [comment]
***@***.***D73616.53B15530]
***@***.***D73616.53B15530]
Oh, I found that when I change the image to 16 bit, there was no any error code. And the picture looks better.
Thank you so much!
By the way, Is this the latest version?


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Rodrigo ***@***.***>
发送时间: 2021年4月20日 18:05
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [StuartLab/MiNA] Error (#32)


Which version of MiNA are you using? What does the user interface look like? Also, do you still get the error if you don't convert to 8-bit?

―

**Comment by RodoVJ** [comment]
No worries! [This is the latest version of MiNA](https://github.com/StuartLab/MiNA/releases/tag/3.0.0). It should have a user interface with more options and allow you to visualize preprocessing steps such as filters.

**Comment by kaccfite** [comment]
Thank you!
You are so nice!
Have a good day!
Yanqiao

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Rodrigo ***@***.***>
发送时间: 2021年4月20日 19:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [StuartLab/MiNA] Error (#32)


No worries! This is the latest version of MiNA<https://github.com/StuartLab/MiNA/releases/tag/3.0.0>. It should have a user interface with more options and allow you to visualize preprocessing steps such as filters.

―

**Comment by kaccfite** [comment]
I just need to download the zip file and replace the old one in different folds, right?

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Rodrigo ***@***.***>
发送时间: 2021年4月20日 19:11
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [StuartLab/MiNA] Error (#32)


No worries! This is the latest version of MiNA<https://github.com/StuartLab/MiNA/releases/tag/3.0.0>. It should have a user interface with more options and allow you to visualize preprocessing steps such as filters.

―

**Comment by RodoVJ** [comment]
That's right. [Here are the installation instructions](https://github.com/StuartLab/MiNA#installation) that explain it more in detail. Although I think you might already have the latest version.

**Comment by kaccfite** [comment]
Thank you!!!!

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

发件人: Rodrigo ***@***.***>
发送时间: 2021年4月20日 19:45
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [StuartLab/MiNA] Error (#32)


That's right. Here are the installation instructions<https://github.com/StuartLab/MiNA#installation> that explain it more in detail. Although I think you might already have the latest version.

―
