### ISSUE TITLE
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: 

### ISSUE THREAD

**Issue by asm16** [StuartLab/MiNA#34]
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\TARUN\Desktop\ICON\fiji-win64\Fiji.app\scripts\MiNA_Analyze_Morphology.py (The system cannot find the file specified)
	at org.scijava.script.ScriptInfo.parseParameters(ScriptInfo.java:294)
	at org.scijava.module.AbstractModuleInfo.initParameters(AbstractModuleInfo.java:189)
	at org.scijava.module.AbstractModuleInfo.inputMap(AbstractModuleInfo.java:139)
	at org.scijava.module.AbstractModuleInfo.getInput(AbstractModuleInfo.java:73)
	at org.scijava.module.DefaultModuleService.assignInputs(DefaultModuleService.java:456)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:239)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:208)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:189)
	at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:187)
	at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:173)
	at MiNAgui.runMiNA(MiNAgui.java:126)
	at MiNAgui.lambda$run$4(MiNAgui.java:233)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: C:\Users\TARUN\Desktop\ICON\fiji-win64\Fiji.app\scripts\MiNA_Analyze_Morphology.py (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at org.scijava.script.process.ScriptProcessorService.process(ScriptProcessorService.java:62)
	at org.scijava.script.ScriptInfo.parseParameters(ScriptInfo.java:290)
	... 47 more
[INFO] Reading available sites from https://imagej.net/
Exception in thread "AWT-EventQueue-0" java.lang.RuntimeException: java.io.FileNotFoundException: C:\Users\TARUN\Desktop\ICON\fiji-win64\Fiji.app\scripts\MiNA_Analyze_Morphology.py (The system cannot find the file specified)
	at org.scijava.script.ScriptInfo.parseParameters(ScriptInfo.java:294)
	at org.scijava.module.AbstractModuleInfo.initParameters(AbstractModuleInfo.java:189)
	at org.scijava.module.AbstractModuleInfo.inputMap(AbstractModuleInfo.java:139)
	at org.scijava.module.AbstractModuleInfo.getInput(AbstractModuleInfo.java:73)
	at org.scijava.module.DefaultModuleService.assignInputs(DefaultModuleService.java:456)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:239)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:208)
	at org.scijava.module.DefaultModuleService.run(DefaultModuleService.java:189)
	at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:187)
	at org.scijava.script.DefaultScriptService.run(DefaultScriptService.java:173)
	at MiNAgui.runMiNA(MiNAgui.java:126)
	at MiNAgui.lambda$run$3(MiNAgui.java:205)
	at javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:2022)
	at javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2348)
	at javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:402)
	at javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:259)
	at javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:252)
	at java.awt.Component.processMouseEvent(Component.java:6539)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6304)
	at java.awt.Container.processEvent(Container.java:2239)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2297)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4904)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4535)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4476)
	at java.awt.Container.dispatchEventImpl(Container.java:2283)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
	at java.awt.EventQueue$4.run(EventQueue.java:733)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.io.FileNotFoundException: C:\Users\TARUN\Desktop\ICON\fiji-win64\Fiji.app\scripts\MiNA_Analyze_Morphology.py (The system cannot find the file specified)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at java.io.FileReader.<init>(FileReader.java:58)
	at org.scijava.script.process.ScriptProcessorService.process(ScriptProcessorService.java:62)
	at org.scijava.script.ScriptInfo.parseParameters(ScriptInfo.java:290)
	... 47 more

**Comment by asm16** [comment]
How to resolve this issue?

**Comment by RodoVJ** [comment]
Hi! 
As you can see from this part of the error:

C:\Users\TARUN\Desktop\ICON\fiji-win64\Fiji.app\scripts\MiNA_Analyze_Morphology.py (The system cannot find the file specified)

The program is looking for a file and can't find it in the path specified. Please make sure to go to that directory and check that the MiNA_Analyze_Morphology.py file is in fact there. Also please make sure to read the installing instructions at the end of the README of this repository to make sure you're placing all the files in their correct location.

Let me know how it goes!
