### ISSUE TITLE
Plugin won't run bc of exception window

### ISSUE THREAD

**Issue by hcha2** [StuartLab/MiNA#38]
Hi,

I am having issues on both Windows and a Mac, running the StuartLab-> MiNA Script -> MiNA Analyze Morphology Plug-in. An exception window comes up and says the following:

(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 51MB of 5930MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.scijava.ui.swing.widget.SwingNumberWidget.lambda$suitableFormat$0(SwingNumberWidget.java:344)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
	at org.scijava.ui.swing.widget.SwingNumberWidget.suitableFormat(SwingNumberWidget.java:344)
	at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:127)
	at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:74)
	at org.scijava.plugin.WrapperService.create(WrapperService.java:65)
	at org.scijava.widget.AbstractInputHarvester.addInput(AbstractInputHarvester.java:110)
	at org.scijava.widget.AbstractInputHarvester.buildPanel(AbstractInputHarvester.java:84)
	at org.scijava.widget.InputHarvester.harvest(InputHarvester.java:67)
	at org.scijava.ui.AbstractInputHarvesterPlugin.process(AbstractInputHarvesterPlugin.java:74)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:152)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more

I keep seeing "Module threw exception" and was wondering what I could do. I have tried uninstalling and installing Fiji and also updated Java to the latest version. Would appreciate any help or advice!

**Comment by junchenile** [comment]
Hi,I have suffered the same problems, have you ever solved this problem.

**Comment by RodoVJ** [comment]
Hello, how are you downloading MiNA?

**Comment by hcha2** [comment]
Hi, I downloaded FiJi, and in Help -> Update... -> Manage Update sites -> added Biomedgroup & StuartLab. Then I restarted Fiji. This is when I started getting the 'Module threw exception' window.

I then to download MiNA another way. I downloaded the contents of the folders in https://github.com/StuartLab/MiNA as a zipped folder and followed the instructions below.

2. Go to your FIJI installation and go to the "Fiji.app" folder. If you're using mac, right click on the FIJI icon and select "Show Package Contents".
3. Move the folder with the name "mina" located in "src" of this repository to jars>Lib (create the folder Lib if it does not already exist).
4. Move the file "MiNA_Analyze_Morphology.py" located at "src>scripts" to "scripts".
5. Move the folder "mina_icons" inside "images".
6. In the "build" folder of this repository you will see a jar file. Move it inside "plugins".
7. Finally, start ImageJ and if you don't have the Biomedroup site installed then click on Help->Update...
Navigate to the update site manager (Manage update sites). Add the "Biomedgroup" site by checking the checkbox beside the site.
Close the site manager dialog (Close) and apply the changes (Apply changes)

Now I get notifications that there are duplicate commands on Fiji and I still get the same 'Module threw exception' window when I try to run the MiNA plug-in.

**Comment by RomainPe** [comment]
Hi, 

Im just having the same problem and I dont know how to resolve it, when i run Mina Analyse an exception window open 

(Fiji Is Just) ImageJ 2.3.0/1.53f51; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 82MB of 9096MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:150)
	at ij.Executer.run(Executer.java:68)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.scijava.ui.swing.widget.SwingNumberWidget.lambda$suitableFormat$0(SwingNumberWidget.java:344)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
	at org.scijava.ui.swing.widget.SwingNumberWidget.suitableFormat(SwingNumberWidget.java:344)
	at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:127)
	at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:74)
	at org.scijava.plugin.WrapperService.create(WrapperService.java:65)
	at org.scijava.widget.AbstractInputHarvester.addInput(AbstractInputHarvester.java:110)
	at org.scijava.widget.AbstractInputHarvester.buildPanel(AbstractInputHarvester.java:84)
	at org.scijava.widget.InputHarvester.harvest(InputHarvester.java:67)
	at org.scijava.ui.AbstractInputHarvesterPlugin.process(AbstractInputHarvesterPlugin.java:74)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:152)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more


I thank you in advance if you have the solution

**Comment by hcha2** [comment]
Hi, I resolved this issue by downloading MiNA through these steps:

1. If you by chance added StuartLab through Help -> Update... -> Manage Update sites, then you must undo that. Go to Help -> Update... -> Manage Update sites and UNCHECK StuartLab.

2. After unchecking StuartLab, go to https://github.com/StuartLab/MiNA as a zipped folder and download the contents of the folders in the website.

3. Go to your FIJI installation and go to the "Fiji.app" folder. If you're using mac, right click on the FIJI icon and select "Show Package Contents".

4. Move the folder with the name "mina" located in "src" of this repository to jars>Lib (create the folder Lib if it does not already exist).

5. Move the file "MiNA_Analyze_Morphology.py" located at "src>scripts" to "scripts".

6. Move the folder "mina_icons" inside "images".

7. In the "build" folder of this repository you will see a jar file. Move it inside "plugins".

8. Finally, start ImageJ and if you don't have the Biomedroup site installed then click on Help->Update...
Navigate to the update site manager (Manage update sites). Add the "Biomedgroup" site by checking the checkbox beside the site.

9. Close the site manager dialog (Close) and apply the changes (Apply changes)

10. Restart Fiji

**Comment by pguptabhm** [comment]
Did as mentioned above. Plug-in still didn't work! Please advise. Thanks
