### ISSUE TITLE
Plugin won't run

### ISSUE THREAD

**Issue by racheljames6** [StuartLab/MiNA#39]
Hello,

I have been trying to run MiNa but keep getting an Exception file (see attachment). I have reinstalled MiNa (including the updates from this site) and added Biomedroup/Stuartlab but am having no luck. I have also asked a colleague to take a look and they too cannot get MiNa to run. Can someone have a look please? Thanks. Rachel
[miNA.docx](https://github.com/StuartLab/MiNA/files/7618316/miNA.docx)
el

**Comment by kyried** [comment]
I am getting the same exception when I try to run the plugin as well, and haven't been able to get the plugin to work for months. Also have reinstalled the plugin and tried on both PC and Mac.

**Comment by kyried** [comment]
I was having this same issue and checked the closed issues section (#38). You need to uninstall through the update window (uncheck Stuart lab) and then manually install the plugin through the github repository.

**Comment by racheljames6** [comment]
Thanks for that. I will have another attempt at downloading MiNa.

**Comment by pguptabhm** [comment]
I having same issues, tried reinstalling the plugin several times and updating Stuartlab/Biomedgroup. It is still not working. Kindly help if possible. Thanks, Priyanka

**Comment by kyried** [comment]
Priyanka, are you installing the plug-in via the update window in ImageJ or by manually putting the files into the imagej plug-in folders? The plug-in should not be installed by the update window in ImageJ. Unselect the Stuart lab repository to delete the files, download the zip from GitHub, and manually place the files into the respective folders as explained on the main GitHub page and I think in a readme in the zip.  Hopefully this helps you install it correctly.

**Comment by pguptabhm** [comment]
I did exactly the same as explained in the GitHub/ readme by unselecting and deleting the Stuart repository files, download zip from GitHub, placing files in the respective folders, but it still showed the same error. I tried both in mac and windows, displaying the same error output.

**Comment by pguptabhm** [comment]
I used this plugin a year ago and it worked fine then. It just doesn't seem to work now, not sure about the cause of the persistent error. appreciate your help,

**Comment by pguptabhm** [comment]
I am seeing the following error after re-installing the plug-in. Let me know if you could advise anything to fix this error. Thanks

[Wed Feb 16 11:45:14 CST 2022] [ERROR] [] null
Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): C:\Users\prigupta\Downloads\Downloads\fiji-win64\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by kyried** [comment]
Priyanka the error you are getting is due to having the old version, at least thats what I think from what I have read on here. Many people on here have had the same issue and it seems the only way to fix it is to manually install the plugin see #31 for what the plugin collaborator says. Are you using the most recent version of ImageJ? I use FIJI instead of the generic ImageJ but it shouldn't matter too much. Also, make sure you have the biomedgroup repository selected as well. 

If you are still having issues, I could probably just send you my FIJI file with the plugin installed to see if that fixes your issue over email.

**Comment by kyried** [comment]
Send me an email at kyle.j.riedmann@vanderbilt.edu if you need more info/help.
