### ISSUE TITLE
ImportError: No module named mina

### ISSUE THREAD

**Issue by CKThompso** [StuartLab/MiNA#43]
I'm trying to get MiNA to work but am having some issues. I made the mistake of initially installing it via Update, but I removed StuartLab from Update and installed using instructions and the file from GitHub. This was an improvement since I could now at least open MiNA. When I click OK with an image open and an ROI selected, I get the error below. 

I am going to guess that something is messed up from when I initially installed it, but hopefully someone can shed some light on this. 

Thanks,

CKT

[ERROR] Traceback (most recent call last):
  File "C:\fiji-win64\Fiji.app\scripts\MiNA_Analyze_Morphology.py", line 41, in <module>
    import mina.statistics 
ImportError: No module named mina

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.import_first(imp.java:1230)
	at org.python.core.imp.import_module_level(imp.java:1361)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx1.f$0(C:/fiji-win64/Fiji.app/scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx1.call_function(C:/fiji-win64/Fiji.app/scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by CKThompso** [comment]
Eh, I figured it out. I had accidentally copied one of the files to the wrong folder during installation. I think I am good now! Thanks for your hard work on this helpful tool!

**Comment by liqinyu123** [comment]
> Eh, I figured it out. I had accidentally copied one of the files to the wrong folder during installation. I think I am good now! Thanks for your hard work on this helpful tool!

I have meeted this same error, could you help to clear which files are moved to the wrong files
