### ISSUE TITLE
Exception shows after I try to run MINA and I can't use it

### ISSUE THREAD

**Issue by JiazhenWang** [StuartLab/MiNA#45]
I installed it following the instruction, but I got a exception and can't run it. The exception is as follow:
(Fiji Is Just) ImageJ 2.3.0/1.51w; Java 1.8.0_172 [64-bit]; Windows 10 10.0; 67MB of 12135MB (<1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:307)
	at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
	at ij.IJ.runPlugIn(IJ.java)
	at ij.Executer.runCommand(Executer.java:137)
	at ij.Executer.run(Executer.java:66)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:303)
	... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 more
Caused by: java.lang.NullPointerException
	at org.scijava.ui.swing.widget.SwingNumberWidget.lambda$suitableFormat$0(SwingNumberWidget.java:344)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.reduce(ReferencePipeline.java:479)
	at java.util.stream.ReferencePipeline.max(ReferencePipeline.java:515)
	at org.scijava.ui.swing.widget.SwingNumberWidget.suitableFormat(SwingNumberWidget.java:344)
	at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:127)
	at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:74)
	at org.scijava.plugin.WrapperService.create(WrapperService.java:65)
	at org.scijava.widget.AbstractInputHarvester.addInput(AbstractInputHarvester.java:110)
	at org.scijava.widget.AbstractInputHarvester.buildPanel(AbstractInputHarvester.java:84)
	at org.scijava.widget.InputHarvester.harvest(InputHarvester.java:67)
	at org.scijava.ui.AbstractInputHarvesterPlugin.process(AbstractInputHarvesterPlugin.java:74)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:152)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more

**Comment by JiazhenWang** [comment]
Solved, I deleted the Staurtlab through upgrade and manually installed it from GitHub, then everything works fine... The imageJ wiki is just telling people wrong way of installing this...

**Comment by zcjtmto** [comment]
Encountered the same issue when trying to install through the installation method mentioned here: https://imagej.net/plugins/mina (do NOT try to follow their instructions)

Instead, I recommend installing via this method (i.e., downloading the source code zip folder): https://forum.image.sc/t/mina-mitochondrial-network-analysis-error-plugins/42831/7

If you have accidentally installed MiNA through the first method you will need to delete the original mina folder to avoid Fiji/ImageJ running the old version. This can be done by going to the Fiji folder (on mac, rightclick on software > "Show Package Contents") then going to plugins > Scripts > Plugins to locate the StuartLab folder, and then deleting it.

I spent many hours searching for the solution so hope this helps!
