### ISSUE TITLE
MiNA plugin not working

### ISSUE THREAD

**Issue by MeenakshiM26** [StuartLab/MiNA#54]
<img width="953" alt="Screenshot 2023-05-22 at 6 04 44 PM" src="https://github.com/StuartLab/MiNA/assets/134338313/1cf9f98d-e83b-4663-bf35-7ee7a40c08a5">
<img width="1010" alt="Screenshot 2023-05-22 at 6 22 32 PM" src="https://github.com/StuartLab/MiNA/assets/134338313/3154c8a5-388a-4ce2-aee9-6d865319a81f">
<img width="1512" alt="Screenshot 2023-05-22 at 6 26 44 PM" src="https://github.com/StuartLab/MiNA/assets/134338313/587e8801-e549-4cdd-bece-1f7d3521e6ed">

Hi,
I have added the Mina plugin as suggested by Alex H.

Installation
You should have [FIJI 35](https://fiji.sc/) installed.
1. Download the contents of this repository as a zipped folder
2. Go to your FIJI installation and go to the “Fiji.app” folder. If you’re using mac, right click on the FIJI icon and select “Show Package Contents”.
3. Move the folder with the name “mina” located in “src” of this repository to jars>Lib (create the folder Lib if it does not already exist).
4. Move the file “MiNA_Analyze_Morphology.py” located at “src>scripts” to “scripts”.
5. Move the folder “mina_icons” inside “images”.
6. In the “build” folder of this repository you will see a jar file. Move it inside “plugins”.
7. Finally, start ImageJ and if you don’t have the Biomedroup site installed then click on Help->Update…
Navigate to the update site manager (Manage update sites). Add the “Biomedgroup” site by checking the checkbox beside the site.
Close the site manager dialog (Close) and apply the changes (Apply changes).

however, after installation when I am running the plugin, it is not working (screenshot attached).
Kindly help.

**Comment by Rayanu** [comment]
Hello, 
I actually have the same issue and I don't know how to solve it. If you found a solution i would appreciate if you shared it

**Comment by MeenakshiM26** [comment]
Hi,
I was struggling with two steps.
Step 5.
I was mistakenly transferring the entire MiNA folder into the "image" folder. I have corrected it and transferred only "mina_icon" inside images.
Step 7.
While updating the site manager and adding "Biomedgroup", I was also adding Stuart Lab. I think that was causing some interference or issues. This confusion occurred as I have followed installation suggestions from Wikipedia before.
This time, I only selected "Biomedgroup" and it worked.
I wish someone could update the installation manual available on wiki. It could have saved so much time and effort.
Hope this might be helpful.
Best,
Meenakshi

**Comment by giampierolago** [comment]
I have the same issue; I've do what you advise in this post but the solution not working for me (both on a Mac and a Windows computer); this is the output:

(Fiji Is Just) ImageJ 2.9.0/1.54e; Java 1.8.0_322 [64-bit]; Windows 10 10.0; 71MB of 5844MB (1%)
 
java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:308)
at net.imagej.legacy.DefaultLegacyHooks.interceptRunPlugIn(DefaultLegacyHooks.java:166)
at ij.IJ.runPlugIn(IJ.java)
at ij.Executer.runCommand(Executer.java:152)
at ij.Executer.run(Executer.java:70)
at java.lang.Thread.run(Thread.java:750)
Caused by: java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
at java.util.concurrent.FutureTask.report(FutureTask.java:122)
at java.util.concurrent.FutureTask.get(FutureTask.java:192)
at net.imagej.legacy.LegacyService.runLegacyCompatibleCommand(LegacyService.java:304)
... 5 more
Caused by: java.lang.RuntimeException: Module threw exception
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
... 1 more
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java.math.BigInteger
at org.scijava.ui.swing.widget.SpinnerNumberModelFactory.createModel(SpinnerNumberModelFactory.java:56)
at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:123)
at org.scijava.ui.swing.widget.SwingNumberWidget.set(SwingNumberWidget.java:74)
at org.scijava.plugin.WrapperService.create(WrapperService.java:65)
at org.scijava.widget.AbstractInputHarvester.addInput(AbstractInputHarvester.java:110)
at org.scijava.widget.AbstractInputHarvester.buildPanel(AbstractInputHarvester.java:84)
at org.scijava.widget.InputHarvester.harvest(InputHarvester.java:67)
at org.scijava.ui.AbstractInputHarvesterPlugin.process(AbstractInputHarvesterPlugin.java:74)
at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
at org.scijava.module.ModuleRunner.run(ModuleRunner.java:152)
at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
... 6 more

Thanks
Giampiero

**Comment by fsangalli72** [comment]
Hi, I also tried the previously written solution but it doesn't work, does anyone have any ideas?

**Comment by nahow97** [comment]
Hi,
I am having a similar issue. I cannot add the Stuart Lab and Biomed plug ins in my Image J download. I am using a Mac and every time I put update link it closes the application and doesn't have the option to add plug-ins.

Could you help me please?

Thank you

**Comment by zelunw** [comment]
Check out this [pull request](https://github.com/StuartLab/MiNA/pull/50/files). Changing `BigInteger` to `Integer` in `MiNA_Analyze_Morphology.py` worked for me
