### ISSUE TITLE
eztables_init_$py.class error

### ISSUE THREAD

**Issue by krw-uw** [StuartLab/MiNA#56]
I had initial error about BigInteger and modified to Integer in Mina_Analyze_Morphology.py.  Now I get past that error, the GUI opens, but when I run it I get following error. Running a recently updated ImageJ/Fiji ver 1.54. Tried again with a fresh fiji install and pulling the mina files from the github rather than the update site and getting same result. 

[ERROR] Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 20, in <module>
ImportError: compiled unit contains version 37 code (38 required): D:\fiji-all-users\Fiji.app\jars\Lib\eztables\__init__$py.class

	at org.python.core.Py.ImportError(Py.java:329)
	at org.python.core.imp.readCodeData(imp.java:396)
	at org.python.core.imp.createFromPyClass(imp.java:284)
	at org.python.core.imp.loadFromSource(imp.java:951)
	at org.python.core.imp.find_module(imp.java:769)
	at org.python.core.imp.import_next(imp.java:1158)
	at org.python.core.imp.import_module_level(imp.java:1350)
	at org.python.core.imp.importName(imp.java:1528)
	at org.python.core.ImportFunction.__call__(__builtin__.java:1285)
	at org.python.core.PyObject.__call__(PyObject.java:433)
	at org.python.core.__builtin__.__import__(__builtin__.java:1232)
	at org.python.core.imp.importOne(imp.java:1547)
	at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:173)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1687)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:255)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:173)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by amaya-hfm** [comment]
Hi did you manage to fix the problem? I'm getting this error message as well
