### ISSUE TITLE
Issue running MiNA, IndexError out of range

### ISSUE THREAD

**Issue by dumbaugh** [StuartLab/MiNA#8]
I have MiNA updated and have tried uninstalling fiji and reinstalling however when I run StuartLab-->MiNA Script -->MiNA Analyze Morphology I keep getting an IndexError: index out of range:1 (see below). I had been using it successfully for 2 hours before that point, now however, it is no longer working. Any advice would be appreciated. 

Traceback (most recent call last):
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 291, in <module>
  File "Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py", line 213, in run
IndexError: index out of range: 1

	at org.python.core.Py.IndexError(Py.java:280)
	at org.python.core.SequenceIndexDelegate.checkIdxAndGetItem(SequenceIndexDelegate.java:63)
	at org.python.core.PySequence.seq___getitem__(PySequence.java:377)
	at org.python.core.PySequence.__getitem__(PySequence.java:373)
	at org.python.pycode._pyx0.run$2(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:287)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyBaseCode.call(PyBaseCode.java:308)
	at org.python.core.PyFunction.function___call__(PyFunction.java:471)
	at org.python.core.PyFunction.__call__(PyFunction.java:466)
	at org.python.core.PyFunction.__call__(PyFunction.java:456)
	at org.python.pycode._pyx0.f$0(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py:291)
	at org.python.pycode._pyx0.call_function(Plugins/StuartLab/MiNA_Scripts/MiNA_Analyze_Morphology.py)
	at org.python.core.PyTableCode.call(PyTableCode.java:171)
	at org.python.core.PyCode.call(PyCode.java:18)
	at org.python.core.Py.runCode(Py.java:1614)
	at org.python.core.__builtin__.eval(__builtin__.java:497)
	at org.python.core.__builtin__.eval(__builtin__.java:501)
	at org.python.util.PythonInterpreter.eval(PythonInterpreter.java:259)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:57)
	at org.python.jsr223.PyScriptEngine.eval(PyScriptEngine.java:31)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at org.scijava.script.ScriptModule.run(ScriptModule.java:160)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:168)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:66)
	at org.scijava.thread.DefaultThreadService$3.call(DefaultThreadService.java:238)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ScienceToolkit** [comment]
What were the input parameters you were using when it crashes? It looks like you probably have a user comment with "=" in it that is not a key value pair (key=value). The possibility that an equals sign is provided as a comment and is not in the form of a key value pair is not handled.

**Comment by dumbaugh** [comment]
You are correct, thank you. I had a user comment that had the column name with no value assigned, e.g. "APAP, Time = 24 hr".
